# GitHub Sponsors configuration
github: dathims

# Alternative donation platforms
buy_me_a_coffee: YOUR_BMAC_USERNAME  # Replace with your Buy Me a Coffee username

# Cryptocurrency donations and Ko-fi
custom: ['https://ko-fi.com/X8X11P0PR3', 'https://github.com/dathims/nocss#support']
